//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("en-US" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("Team Build Screensaver")]
[assembly: AssemblyCopyrightAttribute("Copyright © Jim Liddell")]
