using System.Reflection;
//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;

[assembly: NeutralResourcesLanguageAttribute("en-US" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("TeamBuildScreenSaver")]
[assembly: AssemblyCopyrightAttribute("Copyright © Jim Liddell")]
[assembly: AssemblyProductAttribute("Team Build Screen Saver")]
