// <auto-generated />
using System.Reflection;
//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Runtime.InteropServices;

[assembly: NeutralResourcesLanguageAttribute("")]
[assembly: AssemblyTitleAttribute("TeamBuildScreen.Core")]
[assembly: AssemblyCopyrightAttribute("Copyright © Jim Liddell")]
[assembly: AssemblyProductAttribute("Team Build Screen")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: ComVisibleAttribute(false)]
